version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  other-lambda:
    type: boolean
    default: false
  proxy-lambda:
    type: boolean
    default: false
  infrastructure-dev:
    type: boolean
    default: false
  infrastructure-staging:
    type: boolean
    default: false
  infrastructure-production:
    type: boolean
    default: false
    
jobs:
  unit-test-lambda:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          when: << pipeline.parameters.other-lambda >>
          name: test other-lambda
          command: |
            cd lambdas/other-lambda
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python -m unittest
      - run:
          when: << pipeline.parameters.proxy-lambda >>
          name: test proxy-lambda
          command: |
            cd lambdas/proxy-lambda
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python -m unittest

  tf-init-and-plan-lambda-staging:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install terraform
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - run:
          when: << pipeline.parameters.other-lambda >>
          name: terraform init & plan other-lambda
          command: |
            cd lambdas/other-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
            terraform plan -out=tfplan
      - run:
          when: << pipeline.parameters.proxy-lambda >>
          name: terraform init & plan proxy-lambda
          command: |
            cd lambdas/proxy-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
            terraform plan -out=tfplan

  tf-deploy-lambda-staging:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install terraform
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - run:
          when: << pipeline.parameters.other-lambda >>
          name: terraform init & plan other-lambda
          command: |
            cd lambdas/other-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
            terraform plan -out=tfplan
      - run:
          when: << pipeline.parameters.proxy-lambda >>
          name: terraform init & plan proxy-lambda
          command: |
            cd lambdas/proxy-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
            terraform plan -out=tfplan
      - run:
          when: << pipeline.parameters.other-lambda >>
          name: terraform apply other-lambda
          command: |
            cd lambdas/other-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform apply tfplan
      - run:
          when: << pipeline.parameters.proxy-lambda >>
          name: terraform apply proxy-lambda
          command: |
            cd lambdas/proxy-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform apply tfplan

  deploy-other-lambda-staging:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install terraform
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - run:
          name: terraform init & plan
          command: |
            cd lambdas/other-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
            terraform plan -out=tfplan
      - run:
          name: terraform apply
          command: |
            cd lambdas/other-lambda/env/staging
            export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            terraform apply tfplan

  proxy-lambda: 
      executor: base
      steps:
        - run: 
            command: |
              echo "proxy lambda"
  infrastructure-dev:
      docker:
        - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: terraform init & plan
            command: |
              cd infrastructure/env/dev
              export AWS_ACCESS_KEY_ID=$DEV_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$DEV_SECRET_ACCESS_KEY
              terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
              terraform plan -out=tfplan
  infrastructure-staging:
      docker:
        - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: terraform init & plan
            command: |
              cd infrastructure/env/staging
              export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
              terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
              terraform plan -out=tfplan
        - run:
            name: terraform apply
            command: |
              cd infrastructure/env/staging
              export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
              terraform apply tfplan
  infrastructure-production:
      executor: base
      steps:
        - run: 
            command: |
              echo "infrastructure"
              
workflows:
  lambda-only:
    when:
      and:
        - or: [ << pipeline.parameters.other-lambda >>, << pipeline.parameters.proxy-lambda >> ]
        - not: << pipeline.parameters.infrastructure-staging >>
    jobs:
      - unit-test-lambda
      - tf-init-and-plan-lambda-staging:
          requires:
            - unit-test-lambda
      - tf-deploy-lambda-staging:
          requires:
            - tf-init-and-plan-lambda-staging
          filters:
            branches:
              only:
                - staging

  deploy-infrastructure-staging:
    when: 
      and:
        - << pipeline.parameters.infrastructure-staging >>
        - not: << pipeline.parameters.other-lambda >>
        - not: << pipeline.parameters.proxy-lambda >>
    jobs:
      - infrastructure-staging:
          filters:
            branches:
              only:
                - staging

  deploy-infrastructure-production:
    when: << pipeline.parameters.infrastructure-production >>
    jobs:
      - infrastructure-production:
          filters:
            branches:
              only:
                - main