version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  other-lambda:
    type: boolean
    default: false
  proxy-lambda:
    type: boolean
    default: false
  infrastructure:
    type: boolean
    default: false
    
jobs:
  build-other-lambda:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: test lambda
          command: |
            cd lambdas/other-lambda
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python -m unittest
  deploy-other-lambda:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install terraform
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - run:
          name: terraform init & plan
          command: |
            cd lambdas/other-lambda
            export AWS_ACCESS_KEY_ID=$DEV_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY=$DEV_SECRET_ACCESS_KEY
            terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
            terraform plan -out=tfplan
      - run:
          name: terraform apply
          command: |
            cd lambdas/other-lambda
            terraform apply tfplan

  proxy-lambda: 
      executor: base
      steps:
        - run: 
            command: |
              echo "proxy lambda"
  infrastructure-dev:
      docker:
        - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      steps:
        - run:
            name: terraform init & plan
            command: |
              cd infrastructure/env/dev
              export AWS_ACCESS_KEY_ID=$DEV_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY=$DEV_SECRET_ACCESS_KEY
              terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
              terraform plan -out=tfplan
  infrastructure-staging:
      docker:
        - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      steps:
        - run:
            name: terraform init & plan
            command: |
              cd infrastructure/env/staging
              export AWS_ACCESS_KEY_ID=$STAGING_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
              terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
              terraform plan -out=tfplan
  infrastructure-production:
      executor: base
      steps:
        - run: 
            command: |
              echo "infrastructure"
              
workflows:
  build-deploy-other-lambda:
    when: << pipeline.parameters.other-lambda >>
    jobs:
      - build-other-lambda
      - deploy-other-lambda:
          requires: 
            - build-other-lambda
          filters:
            branches:
              only:
                - staging
      
  build-deploy-proxy-lambda:
    when: << pipeline.parameters.proxy-lambda >> 
    jobs:
      - proxy-lambda
      
  deploy-infrastructure-dev:
    when: << pipeline.parameters.infrastructure-dev >>
    jobs:
      - infrastructure-dev

  deploy-infrastructure-staging:
    when: << pipeline.parameters.infrastructure-staging >>
    jobs:
      - infrastructure-staging

  deploy-infrastructure-production:
    when: << pipeline.parameters.infrastructure-production >>
    jobs:
      - infrastructure-production