version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  other-lambda:
    type: boolean
    default: false
  proxy-lambda:
    type: boolean
    default: false
  infrastructure:
    type: boolean
    default: false
    
jobs:
  build-other-lambda:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: test lambda
          command: |
            cd lambdas/other-lambda
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python -m unittest
  deploy-other-lambda-staging:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: test lambda
          command: |
            cd lambdas/other-lambda
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python -m unittest
  proxy-lambda: 
      executor: base
      steps:
        - run: 
            command: |
              echo "proxy lambda" 
  infrastructure: 
      executor: base
      steps:
        - run: 
            command: |
              echo "infrastructure"   
              
workflows:
  build-deploy-other-lambda:
    when: << pipeline.parameters.other-lambda >>
    jobs:
      - build-other-lambda
      - terraform/fmt:
          checkout: true
          context: terraform
          requires:
            - build-other-lambda
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          requires:
            - terraform/validate
      - terraform/apply:
          checkout: true
          context: terraform
          filters:
            branches:
              only: 
                - staging
          requires:
            - terraform/plan
      
  build-deploy-proxy-lambda:
    when: << pipeline.parameters.proxy-lambda >> 
    jobs:
      - proxy-lambda
      
  deploy-infrastructure:
    when: << pipeline.parameters.infrastructure >>
    jobs:
      - infrastructure