version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  other-lambda:
    type: boolean
    default: false
  proxy-lambda:
    type: boolean
    default: false
  infrastructure:
    type: boolean
    default: false
    
jobs:
  other-lambda:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: test lambda
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m unittest
  proxy-lambda: 
      executor: base
      steps:
        - run: 
            command: |
              echo "proxy lambda" 
  infrastructure: 
      executor: base
      steps:
        - run: 
            command: |
              echo "infrastructure"   
              
workflows:
  build-other-lambda:
    when: << pipeline.parameters.other-lambda >>
    jobs:
      - other-lambda
      
  build-proxy-lambda:
    when: << pipeline.parameters.proxy-lambda >> 
    jobs:
      - proxy-lambda
      
  build-infrastructure:
    when: << pipeline.parameters.infrastructure >>
    jobs:
      - infrastructure